package dev.benedek.sael.ui.reusable

/*
 * Partially generated by LLMs
 */

import androidx.compose.foundation.Canvas
import androidx.compose.foundation.layout.fillMaxWidth
import androidx.compose.foundation.layout.height
import androidx.compose.foundation.progressSemantics
import androidx.compose.material3.ProgressIndicatorDefaults
import androidx.compose.runtime.Composable
import androidx.compose.ui.Modifier
import androidx.compose.ui.geometry.CornerRadius
import androidx.compose.ui.geometry.Offset
import androidx.compose.ui.geometry.Size
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.graphics.drawscope.clipRect
import androidx.compose.ui.unit.Dp
import androidx.compose.ui.unit.LayoutDirection
import androidx.compose.ui.unit.dp

@Composable
fun FlatEdgeLinearProgressIndicator(
    progress: () -> Float,
    modifier: Modifier = Modifier,
    color: Color = ProgressIndicatorDefaults.linearColor,
    trackColor: Color = ProgressIndicatorDefaults.linearTrackColor,
    gapSize: Dp = 4.dp
) {
    // Reads state exclusively during the Draw phase to prevent Layout recomposition overhead
    val coercedProgress = { progress().coerceIn(0f, 1f) }

    Canvas(
        modifier
            .progressSemantics(coercedProgress())
            .fillMaxWidth()
            .height(4.dp)
    ) {
        val width = size.width
        val height = size.height

        if (width <= 0f || height <= 0f) return@Canvas

        val radius = height / 2f
        val cornerRadius = CornerRadius(radius, radius)

        val progressValue = coercedProgress()
        val isLtr = layoutDirection == LayoutDirection.Ltr
        val progressEnd = progressValue * width

        val gap = gapSize.toPx()

        // The gap scales down as progress approaches 0, ensuring the track fills the space when empty
        val activeGap = minOf(progressEnd, gap)

        // Applying a clip rect ensures that the shapes pushed beyond the width/height are sliced flat.
        clipRect(left = 0f, top = 0f, right = width, bottom = height) {
            if (isLtr) {
                // Progress (Flat on the left, Round on the right)
                if (progressEnd > 0) {
                    drawRoundRect(
                        color = color,
                        topLeft = Offset(-radius, 0f), // Shift left so the cap gets clipped flat
                        size = Size(progressEnd + radius, height),
                        cornerRadius = cornerRadius
                    )
                }

                // Track (Round on the left, Flat on the right)
                val trackStart = progressEnd + activeGap
                if (trackStart < width) {
                    drawRoundRect(
                        color = trackColor,
                        topLeft = Offset(trackStart, 0f),
                        size = Size(width - trackStart + radius, height), // Widen right so the cap gets clipped flat
                        cornerRadius = cornerRadius
                    )
                }
            } else {
                // Progress RTL (Flat on the right, Round on the left)
                if (progressEnd > 0) {
                    drawRoundRect(
                        color = color,
                        topLeft = Offset(width - progressEnd, 0f),
                        size = Size(progressEnd + radius, height), // Widen right so the cap gets clipped flat
                        cornerRadius = cornerRadius
                    )
                }

                // Track RTL (Round on the right, Flat on the left)
                val trackEnd = width - (progressEnd + activeGap)
                if (trackEnd > 0) {
                    drawRoundRect(
                        color = trackColor,
                        topLeft = Offset(-radius, 0f), // Shift left so the cap gets clipped flat
                        size = Size(trackEnd + radius, height),
                        cornerRadius = cornerRadius
                    )
                }
            }
        }
    }
}